### PR TITLE
Update _fingerprint.py

### PR DESCRIPTION
**Pull request by helenamrusso**
Code adapted to work with Sirius 4.8.2, with the new command-line interface (>4.4.29).
It seems to be working fine as the outputs are being generated correctly (comparing to old datasets), but please double-check.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Thanks @helenamrusso these changes look great! Are you able to run the unit tests locally and confirm that the tests continue to pass?

**Comment by helenamrusso** [comment]
Hi @ElDeveloper, happy it is ok! Yes, I ran Qemistree with these modifications, and it is working.

**Comment by anupriyatripathi** [comment]
Hi @helenamrusso, thanks for the PRs. I am happy to test your PR it for the test data in the repository and make sure that the unit tests are passing. Could you please share the exact commands you ran to make it work on your dataset? 
Thanks, I look forward to merging this soon.

**Comment by helenamrusso** [comment]
Hi @anupriyatripathi , these are the commands I ran in Qiime2:

source activate qiime2-2020.2

qiime qemistree compute-fragmentation-trees \\
  --i-features Malpighiaceae_Filtered_EtOH80_NEG_Sirius_MergeMSMS.mgf.qza \\
  --p-sirius-path '/Users/helenarusso/Desktop/sirius.app/Contents/MacOS' \\
  --p-n-jobs 8 \\
  --p-ppm-max 20 \\
  --p-profile qtof \\
  --p-maxmz 1200 \\
  --p-tree-timeout 1600 \\
  --p-num-candidates 50 \\
  --p-ionization-mode '[M-H]-' \\
  --p-java-flags "-Djava.io.tmpdir=/Users/helenarusso/ -Xms45G -Xmx60G" \\
  --o-fragmentation-trees Malpigh_Filter_NEG_EtOH80_fragmentation_trees_sirius482.qza 


qiime qemistree rerank-molecular-formulas \\
  --p-sirius-path '/Users/helenarusso/Desktop/sirius.app/Contents/MacOS' \\
  --i-features Malpighiaceae_Filtered_EtOH80_NEG_Sirius_MergeMSMS.mgf.qza \\
  --i-fragmentation-trees Malpigh_Filter_NEG_EtOH80_fragmentation_trees_sirius482.qza \\
  --p-n-jobs 8 \\
  --p-zodiac-threshold 0.98 \\
  --p-java-flags '-Djava.io.tmpdir=/Users/helenarusso/ -Xms45G -Xmx60G' \\
  --o-molecular-formulas Malpigh_Filter_EtOH80_NEG_molecular_formulas_sirius482.qza \\
  --verbose


qiime qemistree predict-fingerprints \\
  --i-molecular-formulas Malpigh_Filter_EtOH80_NEG_molecular_formulas_sirius482.qza \\
  --p-sirius-path '/Users/helenarusso/Desktop/sirius.app/Contents/MacOS' \\
  --p-n-jobs 8 \\
  --p-java-flags '-Djava.io.tmpdir=/Users/helenarusso/ -Xms45G -Xmx60G' \\
  --p-ppm-max 20 \\
  --p-fingerid-db 'all' \\
  --o-predicted-fingerprints Malpigh_Filter_EtOH80_NEG_fingerprints_sirius482.qza

**Pull request closed without merging**
